name: Deploy to Public Repository

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      # If you are using React/Vue/Angular, keep this.
      - name: Install and Build
        working-directory: ./frontend
        env:
          VITE_API_URL: "https://attendance.umutsen.dev"
        run: |
          npm ci
          npm run build
          touch dist/.nojekyll
        # env:
           # CI: false # Uncomment if build fails due to warnings

      # 3. Deploy to the External Repository
      - name: Deploy to External Repository
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          # The repo you want to deploy TO
          repository-name: UmutSen2662/RFIDAttendanceSystemPages
          
          # The name of the secret you created in the Private Repo containing the Private SSH Key
          ssh-key: ${{ secrets.DEPLOY_KEY }}
          
          # The branch in the public repo to push to
          branch: gh-pages
          
          # The folder containing the build output
          # Use 'dist' or 'build' for React/Vue/Vite
          # Use '.' if you are deploying the root of the repo (static files)
          folder: frontend/dist
